### ISSUE TITLE
Misnamed Branch: 'awesome' contains Hypr/Hyprland config files instead of AwesomeWM

### ISSUE THREAD

**Issue by ackonov** [sogreatandpowerfull/dotfiles#9]
Going through the `awesome` branch of your dotfiles repo, I was expecting to find AwesomeWM config files but couldn't. That's when I noticed that the branch actually contains Hypr/Hyprland config files instead.

I believe this to be an oversight, as the branch name and the README indicate that it should house AwesomeWM configs. To avoid confusion, it's important to address the issue.

I suggest you either:
* Consider to rename the branch to accurately reflect the contained Hypr/Hyprland config files.
* Update the branch by replacing Hypr/Hyprland files with AwesomeWM config files to align the branch name `awesome`.

**Comment by sogreatandpowerfull** [comment]
@ackonov Hi 👋🏻 

The `awesome` branch hasn't been updated yet with my latest awesomewm config and I apologize for any misunderstanding caused by this.

I'll make sure to update the branch asap. I understand the importance of maintaining accurate branch names to avoid confusion of others.
